### ISSUE TITLE
Materiales Surtir Granel-Cantidad por surtir

### ISSUE THREAD

**Issue by MiriamdeLeon-Steelgo** [FabianGutierrezSteelgo/IssuesSteelgo#1]
modificar la parte de cantidad por surtir, donde aparezca la resta de la cantidad requerida- surtido
![imagen](https://user-images.githubusercontent.com/24903990/44732309-9b367600-aaaa-11e8-97c0-2cb75ac5366f.png)

seria la cantidad que dice por surtir , en el detalle

**Comment by MiriamdeLeon-Steelgo** [comment]
![imagen](https://user-images.githubusercontent.com/24903990/44732462-f23c4b00-aaaa-11e8-9924-2a914c8b8ac2.png)

**Comment by FabianGutierrezSteelgo** [comment]
Favor de Validar
